language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install codecov

script:
  - python setup.py install
  - python -m unittest discover
  - coverage run --source pychess -m unittest discover

after_success:
  - codecov