language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install codecov

script:
  - python setup.py install
  - python -m unittest discover -s tests
  - coverage run --source pychess -m unittest discover -s tests

after_success:
  - codecov